name: Rust
# run workflow when the condition is met
on:
  # run when code is pushed on the `main` branch
  push:
    branches: [ "main" ]
  # run when a pull request to the `main` branch
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  # job name
  build:
    # os to run the job on support macOS and windows also
    runs-on: ubuntu-latest
    steps:
    # this will get the code and set the git
    - uses: actions/checkout@v4
    # run the build
    - name: Build
      # using cargo to build
      run: cargo build --release
    # for deployment
    - name: make dir
    # create a directory
      run: mkdir app
    # put the app in it
    - name: copy
      run: mv ./target/release/rest-api ./app/rest-api
    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Verify Heroku CLI Installation
      run: heroku --version
      # heroku deployment
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        # key from repository secrets
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # name of the Heroku app
        heroku_app_name: "munki-web-app"
        # email from which the app is uploaded
        heroku_email: "boss@munki.ai"

        # app directory
        appdir: "./app"

        # start command
        procfile: "web: ./rest-api"
        # buildpack is like environment used to run the app
        buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"
